#!/usr/bin/sh

# Set of files which are to be forked into the client/src directory.
files=(
  "iron-doc-api.html"
  "iron-doc-behavior.html"
  "iron-doc-class.html"
  "iron-doc-demo.html"
  "iron-doc-element.html"
  "iron-doc-function.html"
  "iron-doc-hide-bar.html"
  "iron-doc-mixin.html"
  "iron-doc-namespace.html"
  "iron-doc-property.html"
  "iron-doc-summary.html"
  "iron-doc-viewer-behavior.html"
  "iron-doc-viewer-styles.html"
  "iron-doc-viewer.html"
)

# This strips the files of some dependencies and makes some rote changes.
for i in "${files[@]}"
do
  cat 'bower_components/iron-doc-viewer/'$i \
  | sed '1s;^;<!--\'$'\n''Do NOT modify this file.\'$'\n''Generated by portIronDocViewer.sh during install `npm install`.\'$'\n''-->\'$'\n''\'$'\n'';' \
  | sed 's/\.\.\/marked-element\/marked-element.html/mark-down.html/' \
  | sed 's/marked-element/mark-down/' \
  | sed 's/\.\.\(\/polymer\/polymer\.html\)/..\/bower_components\1/' \
  | sed 's/\(\/iron-location\/iron-location\.html\)/\/bower_components\1/' \
  | sed '/import.*prism-/d' \
  | sed '/prism-highlighter/d' \
  | sed 's/\s*prism-theme-default\s*//' \
  | sed 's/\(\s*\)\(Polymer.IronDocViewerBehavior = {\)/\1\/\/ @polymerBehavior\'$'\n''\1\2/' \
  > 'src/'$i
done

# Add additional styles to style sheets.
# additonalStyles="$(<src/iron-doc-viewer-additional-styles.css)"
# awk --assign=additonalStyles="$additonalStyles" '/<\/style>/{print additonalStyles;print;next}1' src/iron-doc-viewer-2-styles.html > .tmp_file
# mv .tmp_file src/iron-doc-viewer-2-styles.html

# additonalStyles="$(<src/iron-doc-summary-additional-styles.css)"
# awk --assign=additonalStyles="$additonalStyles" '/<\/style>/{print additonalStyles;print;next}1' src/iron-doc-summary-styles.html > .tmp_file
# mv .tmp_file src/iron-doc-summary-styles.html
