application: custom-elements-staging
version: 1
runtime: python27
api_version: 1
threadsafe: true
libraries:
- name: ssl
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- hydro
- scripts
- lib
- node_modules

handlers:
- url: /src/(.*\.html)
  upload: client/src/.*\.html
  static_files: client/src/\1
- url: /manifest.json
  upload: client/manifest.json
  static_files: client/manifest.json
- url: /bower_components/(.+\.(js|html|css))
  upload: client/bower_components/(.+\.(js|html|css))
  static_files: client/bower_components/\1
- url: /.*
  upload: client/index.html
  static_files: client/index.html
